# telepathy-spec - Base classes defining the interfaces of the Telepathy framework
#
# Copyright (C) 2005,2006,2007 Collabora Limited
# Copyright (C) 2005,2006 Nokia Corporation
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

from telepathy._generated.constants import \
        CONN_MGR_PARAM_FLAG_REQUIRED, \
        CONN_MGR_PARAM_FLAG_REGISTER, \
        CONN_MGR_PARAM_FLAG_HAS_DEFAULT, \
        \
        CONNECTION_ALIAS_FLAG_USER_SET, \
        \
        CONNECTION_CAPABILITY_FLAG_CREATE, \
        CONNECTION_CAPABILITY_FLAG_INVITE, \
        \
        HANDLE_TYPE_NONE, \
        HANDLE_TYPE_CONTACT, \
        HANDLE_TYPE_ROOM, \
        HANDLE_TYPE_LIST, \
        HANDLE_TYPE_GROUP, \
        \
        CONNECTION_PRESENCE_TYPE_UNSET, \
        CONNECTION_PRESENCE_TYPE_OFFLINE, \
        CONNECTION_PRESENCE_TYPE_AVAILABLE, \
        CONNECTION_PRESENCE_TYPE_AWAY, \
        CONNECTION_PRESENCE_TYPE_EXTENDED_AWAY, \
        CONNECTION_PRESENCE_TYPE_HIDDEN, \
        \
        CONNECTION_STATUS_CONNECTED, \
        CONNECTION_STATUS_CONNECTING, \
        CONNECTION_STATUS_DISCONNECTED, \
        \
        CONNECTION_STATUS_REASON_NONE_SPECIFIED, \
        CONNECTION_STATUS_REASON_REQUESTED, \
        CONNECTION_STATUS_REASON_NETWORK_ERROR, \
        CONNECTION_STATUS_REASON_AUTHENTICATION_FAILED, \
        CONNECTION_STATUS_REASON_ENCRYPTION_ERROR, \
        CONNECTION_STATUS_REASON_NAME_IN_USE, \
        CONNECTION_STATUS_REASON_CERT_NOT_PROVIDED, \
        CONNECTION_STATUS_REASON_CERT_UNTRUSTED, \
        CONNECTION_STATUS_REASON_CERT_EXPIRED, \
        CONNECTION_STATUS_REASON_CERT_NOT_ACTIVATED, \
        CONNECTION_STATUS_REASON_CERT_HOSTNAME_MISMATCH, \
        CONNECTION_STATUS_REASON_CERT_FINGERPRINT_MISMATCH, \
        CONNECTION_STATUS_REASON_CERT_SELF_SIGNED, \
        CONNECTION_STATUS_REASON_CERT_OTHER_ERROR, \
        \
        CHANNEL_CONTACT_SEARCH_STATE_BEFORE, \
        CHANNEL_CONTACT_SEARCH_STATE_DURING, \
        CHANNEL_CONTACT_SEARCH_STATE_AFTER, \
        \
        CHANNEL_TEXT_MESSAGE_FLAG_TRUNCATED, \
        \
        CHANNEL_TEXT_MESSAGE_TYPE_NORMAL, \
        CHANNEL_TEXT_MESSAGE_TYPE_ACTION, \
        CHANNEL_TEXT_MESSAGE_TYPE_NOTICE, \
        CHANNEL_TEXT_MESSAGE_TYPE_AUTO_REPLY, \
        \
        CHANNEL_TEXT_SEND_ERROR_UNKNOWN as CHANNEL_SEND_ERROR_UNKNOWN, \
        CHANNEL_TEXT_SEND_ERROR_OFFLINE as CHANNEL_SEND_ERROR_OFFLINE, \
        CHANNEL_TEXT_SEND_ERROR_INVALID_CONTACT as CHANNEL_SEND_ERROR_INVALID_CONTACT, \
        CHANNEL_TEXT_SEND_ERROR_PERMISSION_DENIED as CHANNEL_SEND_ERROR_PERMISSION_DENIED, \
        CHANNEL_TEXT_SEND_ERROR_TOO_LONG as CHANNEL_SEND_ERROR_TOO_LONG, \
        \
        CHANNEL_TEXT_SEND_ERROR_UNKNOWN, \
        CHANNEL_TEXT_SEND_ERROR_OFFLINE, \
        CHANNEL_TEXT_SEND_ERROR_INVALID_CONTACT, \
        CHANNEL_TEXT_SEND_ERROR_PERMISSION_DENIED, \
        CHANNEL_TEXT_SEND_ERROR_TOO_LONG, \
        \
        CHANNEL_GROUP_CHANGE_REASON_NONE, \
        CHANNEL_GROUP_CHANGE_REASON_OFFLINE, \
        CHANNEL_GROUP_CHANGE_REASON_KICKED, \
        CHANNEL_GROUP_CHANGE_REASON_BUSY, \
        CHANNEL_GROUP_CHANGE_REASON_INVITED, \
        CHANNEL_GROUP_CHANGE_REASON_BANNED, \
        CHANNEL_GROUP_CHANGE_REASON_INVALID_CONTACT, \
        CHANNEL_GROUP_CHANGE_REASON_NO_ANSWER, \
        \
        CHANNEL_GROUP_FLAG_CAN_ADD, \
        CHANNEL_GROUP_FLAG_CAN_REMOVE, \
        CHANNEL_GROUP_FLAG_CAN_RESCIND, \
        CHANNEL_GROUP_FLAG_MESSAGE_ADD, \
        CHANNEL_GROUP_FLAG_MESSAGE_REMOVE, \
        CHANNEL_GROUP_FLAG_MESSAGE_ACCEPT, \
        CHANNEL_GROUP_FLAG_MESSAGE_REJECT, \
        CHANNEL_GROUP_FLAG_MESSAGE_RESCIND, \
        CHANNEL_GROUP_FLAG_CHANNEL_SPECIFIC_HANDLES, \
        CHANNEL_GROUP_FLAG_ONLY_ONE_GROUP, \
        \
        CHANNEL_HOLD_STATE_NONE, \
        CHANNEL_HOLD_STATE_SEND_ONLY, \
        CHANNEL_HOLD_STATE_RECV_ONLY, \
        CHANNEL_HOLD_STATE_BOTH, \
        \
        CHANNEL_PASSWORD_FLAG_PROVIDE, \
        \
        CHANNEL_MEDIA_CAPABILITY_AUDIO, \
        CHANNEL_MEDIA_CAPABILITY_VIDEO, \
        \
        MEDIA_STREAM_TYPE_AUDIO, \
        MEDIA_STREAM_TYPE_VIDEO, \
        \
        MEDIA_STREAM_DIRECTION_NONE, \
        MEDIA_STREAM_DIRECTION_SEND, \
        MEDIA_STREAM_DIRECTION_RECEIVE, \
        MEDIA_STREAM_DIRECTION_BIDIRECTIONAL, \
        \
        MEDIA_STREAM_PENDING_LOCAL_SEND, \
        MEDIA_STREAM_PENDING_REMOTE_SEND, \
        \
        MEDIA_STREAM_ERROR_UNKNOWN, \
        MEDIA_STREAM_ERROR_EOS, \
        \
        MEDIA_STREAM_BASE_PROTO_UDP, \
        MEDIA_STREAM_BASE_PROTO_TCP, \
        \
        MEDIA_STREAM_TRANSPORT_TYPE_LOCAL, \
        MEDIA_STREAM_TRANSPORT_TYPE_DERIVED, \
        MEDIA_STREAM_TRANSPORT_TYPE_RELAY, \
        \
        MEDIA_STREAM_STATE_DISCONNECTED, \
        MEDIA_STREAM_STATE_CONNECTING, \
        MEDIA_STREAM_STATE_CONNECTED, \
        \
        PROPERTY_FLAG_READ, \
        PROPERTY_FLAG_WRITE

# Backwards compatibility
from telepathy._generated.constants import \
        HANDLE_TYPE_NONE as CONNECTION_HANDLE_TYPE_NONE, \
        HANDLE_TYPE_CONTACT as CONNECTION_HANDLE_TYPE_CONTACT, \
        HANDLE_TYPE_ROOM as CONNECTION_HANDLE_TYPE_ROOM, \
        HANDLE_TYPE_LIST as CONNECTION_HANDLE_TYPE_LIST, \
        HANDLE_TYPE_GROUP as CONNECTION_HANDLE_TYPE_GROUP
